import type { NextPage } from 'next';
import Head from 'next/head';
import { testStore } from 'store';
import { observer } from 'mobx-react';
import { useEffect } from 'react';
import cn from 'classnames';

const Home: NextPage = () => {
  const {
    counter,
    increment,
    decrement,
    inputStr,
    editStr,
    infoTitle,
    loadInfo,
    loadInfoErro,
  } = testStore;

  const styleTest = cn('test1', { test2: true });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styleTest}>{counter}</div>
      <button onClick={increment}>+</button>
      <button onClick={decrement}>-</button>
      <input
        type='text'
        name='input'
        value={inputStr}
        onChange={(e) => editStr((e.target as HTMLInputElement)?.value)}
      />
      <button onClick={loadInfo}>async load</button>
      <button onClick={loadInfoErro}>async load</button>
      {infoTitle && <div>{infoTitle}</div>}
      {/* {info.map((el) => (
        <div key={el.id}>
          {el.title}/{el.hunting}
        </div>
      ))} */}
    </div>
  );
};

export default observer(Home);
