import type { NextPage } from 'next';
import Head from 'next/head';
import { testStore } from 'store';
import { observer } from 'mobx-react';

const Home: NextPage = () => {
  const { counter, increment, decrement, inputStr, editStr } = testStore;
  const a = { a: 1, b: 2 };
  console.log(counter, inputStr);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>{counter}</div>
      <button onClick={increment}>+</button>
      <button onClick={decrement}>-</button>
      <input
        type='text'
        name='input'
        value={inputStr}
        onChange={(e) => editStr((e.target as HTMLInputElement)?.value)}
      />
    </div>
  );
};

export default observer(Home);
